### ISSUE TITLE
希望能把每次更新添加到Release

### ISSUE THREAD

**Issue by FledgeXu** [kslr/nyaa-peel#1]
希望能把每次更新添加到Release

**Comment by kslr** [comment]
每次更新测试没有问题了，我就会发布到Chrome Store
这个频率不适合做release吧
接下来也基本是适配更多的图床

**Comment by FledgeXu** [comment]
我觉得还是可以做个release当作备用的分发渠道。

**Comment by kslr** [comment]
现在可以从release下载crx文件了

**Comment by FledgeXu** [comment]
OK
